### ISSUE TITLE
Bug Fix Request: Prompt to update to 2.8.1 breaks Sketch Measure

### ISSUE THREAD

**Issue by JordanTranchina** [ellunium/sketch-measure-latest#16]
Hi @ellunium ,

When I download your plugin I am prompted to update to Sketch Measure v2.8.1 from @utom . Sadly that one is no longer updated.
In addition, whenever I update to 2.8.1 from @utom Sketch Measure becomes broken and I am not able to Spec Export (gets hung at the beginning of the Spec Export loading pop-up). 

Is it possible for you to add some code that stops your plugin from searching for updates from @utom 's original code?

Many thanks for all you've done with this fork, very helpful!

Cheers,
Jordan

**Comment by ellunium** [comment]
Hi @JordanTranchina, thanks for reporting. 

I have stopped pushing more changes or fixes because I don’t want my fork to deviate too much from @utom 's masterpiece and original plugin. I don’t want my fork to become the main reference for this plugin. I see it only as a temporary fix for me, the community and people I work with, until @utom gets back to pushing more improvements to the original one when and if he has time to do so. 

The idea of leaving it so like this is that @utom would pick it up back again and whomever came to the fork, would be organically sent back to the original plugin.
