### ISSUE TITLE
2.8.0不兼容10.15，导出失败，希望解决一下，十分感谢！！

### ISSUE THREAD

**Issue by Galaxyxinwei** [ellunium/sketch-measure-latest#6]
2.8.0不兼容10.15，导出失败，选择完导出文件夹后插件崩溃，无法导出，希望解决一下，十分感谢！！

**Comment by alexandwich** [comment]
嗨，有个办法可以解决：

打开你的终端粘贴下面的代码执行（可能会要求你输入开机密码）：
`sudo xattr -r -d com.apple.quarantine /Users/${USER}/Library/Application\ Support/com.bohemiancoding.sketch3/Plugins/Sketch\ Measure.sketchplugin/Contents/Sketch/SMFramework.framework/SMFramework`

**Comment by JacqueH** [comment]
Here is a possibly easier way to let a quarantined plugin to run. See the instructions here https://www.3dquakers.com/forester-on-catalina/ but imagine that it's describing sketch-measure-latest instead of 'Forester.'
You will be reminded that you may be compromising your machine's security. I make no claim that doing this is safe or wise or anything. Do it at your own risk.
I don't know how to reverse this, either, which would be a nice thing to know.

**Comment by qingyuan626** [comment]
楼上终端粘贴代码不管用
